apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: flattrack-db
spec:
  enableConnectionPooler: true
  connectionPooler:
    mode: session
    resources:
      requests:
        cpu: 250m
        memory: 100Mi
      limits:
        cpu: "1"
        memory: 100Mi
  teamId: "flattrack"
  volume:
    size: 1Gi
  numberOfInstances: 2
  users:
    flattrack:  # database owner
    - superuser
    - createdb
  databases:
    flattrack: flattrack  # dbname: owner
  postgresql:
    version: "12"
