apiVersion: apps/v1
kind: Deployment
metadata:
  name: flattrackio-site
  namespace: flattrackio-site
  labels:
    environment: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flattrackio-site
  template:
    metadata:
      labels:
        app: flattrackio-site
        environment: production
    spec:
      automountServiceAccountToken: false
      containers:
      - name: flattrackio-site-blog
        image: ${CI_REGISTRY_IMAGE}:${APP_VERSION}
        imagePullPolicy: IfNotPresent
        securityContext:
          readOnlyRootFilesystem: true
          runAsUser: 1000
          runAsGroup: 1000
          allowPrivilegeEscalation: false
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8080
        env:
          - name: TZ
            value: "Pacific/Auckland"
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 2
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 2
          periodSeconds: 10
        resources:
          requests:
            memory: 15Mi
            cpu: 20m
          limits:
            memory: 15Mi
            cpu: 20m
