apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: flattrackio-site
  namespace: flattrackio-site
spec:
  minReplicas: 2
  maxReplicas: 10
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: flattrackio-site
  targetCPUUtilizationPercentage: 80
